package zp_test.springboot_server.zp.entity;

import zp_test.springboot_server.zp.entity.base.BaseEntity;

public class TestEntity extends BaseEntity {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.id
     *
     * @mbggenerated Mon May 21 18:24:25 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.test1
     *
     * @mbggenerated Mon May 21 18:24:25 CST 2018
     */
    private String test1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.test2
     *
     * @mbggenerated Mon May 21 18:24:25 CST 2018
     */
    private String test2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test.id
     *
     * @return the value of t_test.id
     *
     * @mbggenerated Mon May 21 18:24:25 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test.id
     *
     * @param id the value for t_test.id
     *
     * @mbggenerated Mon May 21 18:24:25 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test.test1
     *
     * @return the value of t_test.test1
     *
     * @mbggenerated Mon May 21 18:24:25 CST 2018
     */
    public String getTest1() {
        return test1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test.test1
     *
     * @param test1 the value for t_test.test1
     *
     * @mbggenerated Mon May 21 18:24:25 CST 2018
     */
    public void setTest1(String test1) {
        this.test1 = test1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test.test2
     *
     * @return the value of t_test.test2
     *
     * @mbggenerated Mon May 21 18:24:25 CST 2018
     */
    public String getTest2() {
        return test2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test.test2
     *
     * @param test2 the value for t_test.test2
     *
     * @mbggenerated Mon May 21 18:24:25 CST 2018
     */
    public void setTest2(String test2) {
        this.test2 = test2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test
     *
     * @mbggenerated Mon May 21 18:24:25 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", test1=").append(test1);
        sb.append(", test2=").append(test2);
        sb.append("]");
        return sb.toString();
    }
}