server:
  context-path: /
  port: 80

logging:
  config: classpath:logback.xml


#mysql
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=true&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

#mybatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.zp.dao.ext


#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

